version: '3'

services:
  server_no2_1:
    build:
      context: ./server
    environment:
      - server_port=7000
#    ports:
#      - "7000:7000"
    networks:
      - app_net

  server_no2_2:
    build:
      context: ./server
    environment:
      - server_port=7001
#    ports:
#      - "7001:7001"
    networks:
      - app_net

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server_no2_1
      - server_no2_2
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
